services:

  config-server:
    image: localhost:443/library/config-server:1.0.0
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8888"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    networks:
      - microservices

  discovery-service:
    image: localhost:443/library/discovery-service:1.0.0
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_HOSTNAME_DISCOVERY: discovery-service
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8761"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
    depends_on:
      config-server:
        condition: service_healthy

  gateway:
    image: localhost:443/library/gateway:1.0.0
    container_name: gateway
    ports:
      - "8222:8222"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_HOSTNAME_GATEWAY: gateway
      EUREKA_DEFAULT_ZONE: http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8222"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
    depends_on:
      discovery-service:
        condition: service_healthy

  user-service:
    image: localhost:443/library/user-service:1.0.0
    container_name: user-service
    ports:
      - "8090:8090"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://discovery-service:8761/eureka
      EUREKA_HOSTNAME_USER: user-service
      MONGO_HOST: mongo_db
      MONGO_USERNAME: ${MONGO_ROOT_USER}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8090"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
    depends_on:
      gateway:
        condition: service_healthy
      mongo_db:
        condition: service_healthy

  mongo_db:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  mongo_data: